### ISSUE TITLE
NPE in org.openlca.io.ilcd.output.ExportDispatch

### ISSUE THREAD

**Issue by littlebunch** [GreenDelta/olca-modules#2]
There's a small bug in the checkRunFlowExport method where the Flow object parameter is not being instantiated in the FlowExport object.  Thus, when the FlowExport's run method is called it blows on an NPE when it calls makeDataSetInfo() which is expecting the  flow attribute to have been initialized.  

One fix is to instantiate the FlowExport object with the FlowExport(database,target,flow)  signature;  In our local branch I chose to modify the FlowExport run method by adding this.flow=flow to the first line.

This problem also occurs in checkRunFlowPropertyExport and checkRunActorExport for the same reason and put a similar mod in ActorExport and FlowPropertyExport.

I can put in a pull request on our branch.  Or, you can apply your preferred fix and I'll merge.

**Comment by msrocka** [comment]
Hi Gary,

I think this is already fixed in the current master branch. In the current [FlowExport](https://github.com/GreenDelta/olca-modules/blob/master/olca-io/src/main/java/org/openlca/io/ilcd/output/FlowExport.java) the flow is assigned in the run method:

```java
public class FlowExport {
    ...
    public org.openlca.ilcd.flows.Flow run(Flow flow) throws DataStoreException {
        this.flow = flow;
```

There is a [commit from November 2013](https://github.com/GreenDelta/olca-modules/commit/1af388eacd179b07b66108949cb2d1ddea29ce96) which fixed these issues. Is this correct?

Best regards,
Michael
